### ISSUE TITLE
Need more info

### ISSUE THREAD

**Issue by LonFas** [snsten/Klein#10]
Please give info about "3 pin slide switch" and "click button" what you used in this  [place](https://github.com/snsten/Klein/blob/main/docs/images/buildguide/Trackpad_Resistor.JPG?raw=true) I can't find compatible. 

And how solder the battery correctly in wireless mode? I (at link higher) saw what battery soldered to (+) (-) pins, but at your [instructions](https://github.com/snsten/Klein/blob/main/docs/buildguides/buildguide_wireless.md#battery) everything is somehow less clear. 

---

I promise to make an MR, to adding the information that I needed to get a working keyboard :)

**Comment by snsten** [comment]
The BOM directory contains all the part information.
The reset switch is https://tech.alpsalpine.com/e/products/detail/SKRTLAE010/ and the power switch is https://tech.alpsalpine.com/e/products/detail/SSAJ110100/

For battery you can solder the battery to +- on the PCB directly or use the JST connector. 
I will update battery instructions with images in docs for clarity.
