### ISSUE TITLE
Regarding battery

### ISSUE THREAD

**Issue by regisksc** [snsten/Klein#13]
Firstly, I apologize for my being so noob on this, but I was wondering what would be the issues of placing a larger capacity 3.7 battery over where the trackpad mount was supposed to go(building wireless ofc). I found some 1800mah batteries that are about 40 by 40 mm and 6mm high. But in your guide you suggest not to surpass 3.5mm. Considering I'll print the case and looks are not the most important, would it work placing such battery on top of the XIAOs?

A second doubt would be how can I send the pcb for manufacturing, could you add an explanation on that in the build guide?

**Comment by snsten** [comment]
- The battery suggestion is for when you are placing it between the pcb and case. If it is on top you can use the battery you described. 
- Placing on top of XIAO directly might not be a good idea, you can get 2 laser cut acrylic covers and place the battery in between them. 
- You can import the project file inside pcb dir in KiCad and export gerbers as explained here https://jlcpcb.com/help/article/16-How-to-generate-Gerber-and-Drill-files-in-KiCad-6
- I have added gerbers in releases for convenience but you can diy. Will add the instructions to build guide soon.

P.S.: [No such thing as a stupid question](https://en.wikipedia.org/wiki/No_such_thing_as_a_stupid_question)
