### ISSUE TITLE
Clearance of diodes and choc sockets

### ISSUE THREAD

**Issue by AlexBaldwin42** [snsten/Klein#7]
On the outside column while using the SOD123 diodes they interfere with the choc sockets.  Still usable by soldering the diodes offset down about a millimeter.

**Comment by snsten** [comment]
Can you check if having diodes and switches on the same side and sockets at the other side of PCB have this issue as shown in the attached image. I have not tested with a complete choc build but I think it should work.

![Diode](https://user-images.githubusercontent.com/42868640/201963294-9038b430-3065-4499-9bb4-135e39e7a340.JPG)

**Comment by AlexBaldwin42** [comment]
![Screenshot_20221115-182936_Gallery.jpg](https://user-images.githubusercontent.com/1578592/202061161-6a09f2f4-de79-458d-8f99-dc22db303d3b.jpg)
Here is the clearance i was talking about.  

There are no clearance issues with the switches when the diodes are mounted to the opposite side so thats a solution.

**Comment by snsten** [comment]
I was aware of this issue that's why I had reversible diodes footprint, keeping the issue open might change the position of the diode in next revision.

P.S. White PCB looks great.

**Comment by snsten** [comment]
> Can you check if having diodes and switches on the same side and sockets at the other side of PCB have this issue as shown in the attached image. I have not tested with a complete choc build but I think it should work.
> 
> ![Diode](https://user-images.githubusercontent.com/42868640/201963294-9038b430-3065-4499-9bb4-135e39e7a340.JPG)

Issue with using diode on top was that it interfered with the switchplate in case of choc build.
Fixed the diode placement in the latest commit.
